name: web_project
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jermaine Oppong <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shelf: any
  shelf_static: any

dev_dependencies:
  build_runner: ^1.7.4
  build_web_compilers: ^2.9.0
